module window {

    interface LJMediaPlayer { 
        void setVolume(in int volume); 
        void setMuted(in boolean b);
        boolean getMuteStatus();
        int getCurrentVolume();
    };

}


