module window {

    interface LJMediaPlayer { 
        void setVolume(in long volume); 
        void setMuted(in boolean b);
        boolean getMuteStatus();
        long getCurrentVolume();
    };

}


